### ISSUE TITLE
Rewrite content descriptions

### ISSUE THREAD

**Issue by RadCraftplay** [RadCraftplay/Custom-CSGO-SDK-Launcher#11]
### TODO:
- [x] "FMPONE's video tutorials"
- [x] "Counter-Strike Global Offensive Level Design Boot Camp"
- [x] "Man vs. Engine"
- [x] "Optimization Testing in Source Engine"

**Comment by RadCraftplay** [comment]
Done!
Pull request #13
