### ISSUE TITLE
Add new application launcher

### ISSUE THREAD

**Issue by RadCraftplay** [RadCraftplay/Custom-CSGO-SDK-Launcher#20]
### About
New application launcher will allow users to launch custom applications (Sledge, 3ds Max, Photoshop or just everything that user needs in case he doesn't want to use deafult SDK applications)

### TODO:
* [x] ~~Add base for launcher~~
* [x] ~~Add _"App launcher"_ tab~~
  * [x] ~~Add _"Use new launcher"_ setting~~
  * [x] ~~Add way to customize buttons~~
* [x] ~~Add more App Templates~~
  * [x] ~~Add _"Custom"_ template~~
    * [x] ~~Tweak CustomAppConfigurationDialog~~
  * [x] ~~Add _"Java application"_ template~~
  * [x] ~~**[BUG]** Fix dialogs showing up in taskbar~~
* [x] ~~**[BUG]** Fix old application launcher not restoring buttons~~
