### ISSUE TITLE
Add feedback system

### ISSUE THREAD

**Issue by RadCraftplay** [RadCraftplay/Custom-CSGO-SDK-Launcher#21]
### Description:
Feedback system would help developers to focus on most useful and important functions of an application.

### Example idea of feedback system:
After few weeks/months after first launch of the CSDKL users would be asked for taking part in survey. If user clicked "yes", he would be redirected to survey on google docs.

### TODO:
- [x] Create survey on google docs
- [x] Add feedback system
  - [x] Add gui and functionality
  - [x] Add delay system
  - [x] Add setting "Disable feedback notifications"
  - [x] Add "Send feedback" button inside settings
  - [x] Feedback system running in separated task

**Comment by RadCraftplay** [comment]
Added in #23
