### ISSUE TITLE
New data managing system

### ISSUE THREAD

**Issue by RadCraftplay** [RadCraftplay/Custom-CSGO-SDK-Launcher#27]
### Description: 
New data managing system will simplify work with files a lot. Instead of creating new class, devs have to write single line of code

### TODO:
- [x] Add base for new data manager
- [x] Add serializers
  - [x] XmlFileSerializer
  - [x] XmlStringSerializer
  - [x] BinaryFileSerializer
  - [x] BinaryStringSerializer
- [x] Add TryLoad method
- [ ] Add managers
  - [x] Add managers for (profiles and templates)
  - [x] Add manager for apps
  - [ ] Add manager for community content
    - [ ] Fix XmlStringSerializer not working with ContentGroup class
