### ISSUE TITLE
Add sdklauncher:// protocol

### ISSUE THREAD

**Issue by RadCraftplay** [RadCraftplay/Custom-CSGO-SDK-Launcher#29]
### TODO:
- [x] Create separated program registering extensions
  - [x] Add protocol registration method
- [x] Add _"Register protocol"_ setting (enabled by default)
  - [x] Add _"RegisterProtocol"_ config variable

#### Why is separated application needed?
To add and remove registry keys application needs to gain administrator privileges. It would be very annoying for average user to confirm UAC dialog every time he starts tool, that is needed to work. I have decided that separated application will run every time user changes association settings, so he will be asked for confirmation only when it's necessarry
